config/routes.rb
Dailyjournal::Application.routes.draw do
  get "sessions/new"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "search" => "entries#index"
  resources :users
  
  resources :entries do
    collection { post :import }
  end

  resources :sessions
  resources :friendships

  root 'users#new'

end

app/models/entry.rb
class Entry < ActiveRecord::Base

	acts_as_taggable
	 belongs_to :user



  def self.to_csv
  	require 'csv'

    CSV.generate do |csv|
      csv << column_names
      all.each do |entry|
      	name = Highrise::Person.where("id"=>entry.attributes["contact"]).first.attributes["first_name"] + " " + Highrise::Person.where("id"=>entry.attributes["contact"]).first.attributes["last_name"]
		csv << [entry.attributes["id"].to_s,entry.attributes["entry_text"],name,entry.attributes["tags"][0].to_s,Highrise::Kase.where("id"=>entry.attributes["case"]).first.attributes["name"],entry.attributes["created_at"].to_s,entry.attributes["updated_at"].to_s]
      end
    end
  end

  def self.search(search)
		if search
		   if search.include?("@")
		   	search["@"]=""
		   	search=search.split(",")
		   	Entry.tagged_with(search,:any=>true)
		   else
		    find(:all, :conditions => ['entry_text LIKE ?', "%#{search}%"])
		   end
		else
		    find(:all)
		end
	end


	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
		   Entry.create! row.to_hash
		end
	end


end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @tasks = Highrise::Task.find(:all)
    @entries = current_user.entries.order('created_at').search(params[:search])
    @entries_csv = current_user.entries
    respond_to do |format|
      format.html
      format.csv { send_data @entries_csv.to_csv }
      format.rss { render :layout => false }
    end


  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  def export

  end


  # GET /entries/new
  def new
    @entry = current_user.entries.new
    @contacts = Highrise::Person.find(:all)
    @cases = Highrise::Kase.find(:all)
    @tags = Highrise::Tag.find(:all)

  end

  # GET /entries/1/edit
  def edit
    @cases = Highrise::Kase.find(:all)
    @contacts = Highrise::Person.find(:all)
    @cases = Highrise::Kase.find(:all)
    @tags = Highrise::Tag.find(:all)
    @entry = Entry.find(params[:id])
    if !@entry.contact.nil?
      @contact = Highrise::Person.where("id"=>@entry.contact.to_i).first
    end
    if !@entry.case.nil?
      @case = Highrise::Kase.where("id"=>@entry.case.to_i).first
    end
    

  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.new(entry_params)
    @entry.contact = params["contact"]
    @entry.visibility = params["visibility"]
 
    if !params["tags"].kind_of?(String)&& !params["tags"].nil?
      for t in params["tags"]  
        @entry.tag_list << t 
      end
    else
      @entry.tag_list << params["tags"]
    end

    @entry.case = params["case"]
    
    if !@entry.contact.nil?
      n = Highrise::Note.new(:body=>@entry.entry_text,"subject-type"=>"Party","subject-id"=>@entry.contact.to_i)
      n.save
    end

    if !@entry.case.nil?
      n = Highrise::Note.new(:body=>@entry.entry_text,"subject-type"=>"Kase","subject-id"=>@entry.case.to_i)
      n.save
    end

    respond_to do |format|
      if @entry.save
        format.html { redirect_to '/entries', notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { redirect_to '/entries/new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    @entry.contact = params["contact"]
    @entry.tag_list=[]
    @entry.visibility = params["visibility"]


    if !params["tags"].kind_of?(String) && !params["tags"].nil?
      for t in params["tags"]  
        @entry.tag_list << t
      end
    else
      @entry.tag_list  << params["tags"]
    end

    @entry.case = params["case"]
    
    if !@entry.contact.nil?
      n = Highrise::Note.new(:body=>@entry.entry_text,"subject-type"=>"Party","subject-id"=>@entry.contact.to_i)
      n.save
    end

    if !@entry.case.nil?
      n = Highrise::Note.new(:body=>@entry.entry_text,"subject-type"=>"Kase","subject-id"=>@entry.case.to_i)
      n.save
    end

    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to '/entries', notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  def import
    Entry.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:entry_text)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
    <script type="text/javascript" charset="utf-8">

function assignList()
{
  $('#case_first_list :selected').each(function(i,selected)
  {
    if($("#case_second_list  option[value='"+selected.value+"']").val()==undefined){
      $('#case_second_list').append('<option selected="selected" value="'+selected.value+'">'+selected.text+'</option>');
      $("#case_first_list  option[value='"+selected.value+"']").remove();
    }
  });

}

function unassignList()
{
  $('#case_second_list :selected').each(function(i,selected)
  {
    if($("#case_first_list  option[value='"+selected.value+"']").val()==undefined){
      $('#case_first_list').append('<option value="'+selected.value+'">'+selected.text+'</option>');
      $("#case_second_list  option[value='"+selected.value+"']").remove();
    }else{
      $("#case_second_list  option[value='"+selected.value+"']").remove();
    }
  });

}


function assignListCon()
{
  $('#contact_first_list :selected').each(function(i,selected)
  {
    if($("#contact_second_list  option[value='"+selected.value+"']").val()==undefined){
      $('#contact_second_list').append('<option selected="selected" value="'+selected.value+'">'+selected.text+'</option>');
      $("#contact_first_list  option[value='"+selected.value+"']").remove();
    }
  });

}

function unassignListCon()
{
  $('#contact_second_list :selected').each(function(i,selected)
  {
    if($("#contact_first_list  option[value='"+selected.value+"']").val()==undefined){
      $('#contact_first_list').append('<option value="'+selected.value+'">'+selected.text+'</option>');
      $("#contact_second_list  option[value='"+selected.value+"']").remove();
    }else{
      $("#contact_second_list  option[value='"+selected.value+"']").remove();
    }
  });

}


function assignListTag()
{
  $('#tag_first_list :selected').each(function(i,selected)
  {
    if($("#tag_second_list  option[value='"+selected.value+"']").val()==undefined){
      $('#tag_second_list').append('<option selected="selected" value="'+selected.value+'">'+selected.text+'</option>');
      $("#tag_first_list  option[value='"+selected.value+"']").remove();
    }
  });

}

function unassignListTag()
{
  $('#tag_second_list :selected').each(function(i,selected)
  {
    if($("#tag_first_list  option[value='"+selected.value+"']").val()==undefined){
      $('#tag_first_list').append('<option value="'+selected.value+'">'+selected.text+'</option>');
      $("#tag_second_list  option[value='"+selected.value+"']").remove();
    }else{
      $("#tag_second_list  option[value='"+selected.value+"']").remove();
    }
  });

}



$(document).ready(function(){

$('#case_first_list').dblclick(function(){
    assignList();
  });
  $('#case_second_list').dblclick(function(){
    unassignList();
  });

  $('#contact_first_list').dblclick(function(){
    assignListCon();
  });
  $('#contact_second_list').dblclick(function(){
    unassignListCon();
  });

    $('#tag_first_list').dblclick(function(){
    assignListTag();
  });
  $('#tag_second_list').dblclick(function(){
    unassignListTag();
  });
});



    </script>


<%= render template: "/layouts/sidebar" %>
<div class="main">
<p class="page-header">Edit</p>


<%= form_for @entry, :html => { :class => "form-horizontal entry" } do |f| %>

  <% if @entry.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>





  <div class="form-group">
    <%= f.label :entry_text, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :entry_text, :class => 'form-control',:size => "30x10" %>
    </div>
  </div>

  <div class="form-group">

 <%= f.label :cases, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">

   <select id="case_first_list" multiple="multiple" style="width:100px;">
    <% for c in @cases %>
      <option value=<%= c.id %>><%= c.name %>
      </option> 
    <% end %>
  </select>
  <select id="case_second_list" multiple="multiple" name="case" style="width:100px;">
    <%if !@case.nil? %>
      <option value=<%= @case.attributes["id"] %>>
        <%= @case.attributes["name"] %>
      </option>
    <% end %>
  </select>

</div>
  </div>

  <div class="form-group">


 <%= f.label :contacts, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">

   <select id="contact_first_list" multiple="multiple" style="width:100px;">
    <% for c in @contacts %>
      <option value=<%= c.id %>><%= c.name %>
      </option> 
    <% end %>
  </select>
   <select id="contact_second_list" multiple="multiple" name="contact" style="width:100px;">
    <% if !@contact.nil? %>
      <option value=<%= @contact.attributes["id"] %>><%= @contact.attributes["first_name"] + " " + @contact.attributes["last_name"] %></option>
    <% end %>
  </select>
</div>
  </div>

    <div class="form-group">

 <%= f.label :tags, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">

   <select id="tag_first_list" multiple="multiple" style="width:100px;">
    <% for t in @tags %>
      <option value=<%= t.id %>><%= t.name %>
      </option> 
    <% end %>
  </select>

     <select id="tag_second_list" multiple="multiple" name="tags" style="width:100px;">
        <% for t in @entry.tags %>
            <option selected="selected" value=<%= t.name %>><%=  Highrise::Tag.find(:all).find(:id=>t.name.to_i).first.name
 %>
        <% end %>
    </select>


</div>
  </div>
 <div class="form-group">

 <%= f.label :visibility, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <select id="visibility" name="visibility">
      
      <% if @entry.visibility==true %>
        <option value="true">Everyone in my group</option>
        <option value="false">Me</option>
      <% else %>
        <option value="false">Me</option>
        <option value="true">Everyone in my group</option>
      <% end %>

    </select>
  </div>
</div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                entries_path, :class => 'btn btn-default' %>
    </div>
  </div>


<% end %>

</div>

app/views/entries/edit.html.erb
<%- model_class = Entry -%>

<%= render :partial => 'form' %>

app/views/entries/index.html.erb
<h3 class="header-title">Daily Journal</h3>

<!-- 
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_entry_path,
            :class => 'btn btn-primary' %>
-->
<div class="row">
<form class="navbar-form navbar-left" action="/entries/new" style="float:left;margin-left: 190px;padding-right:0px;">
    <button type="submit" class="btn btn-default">New Entry</button>
</form>
<form class="navbar-form navbar-left" role="search" action="/search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search" name="search">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>

<p style="color:#777777;margin-top:15px;">Use @tag1,tag2,tag3 to search by tags</p>
</div>







<%= render template: "/layouts/sidebar" %>

<div class="main">
<p class="page-header">Getting started</p>


<%= link_to 'Export CSV', '/entries.csv' %>
<%= link_to 'RSS', '/entries.rss' %>

<table>

<tbody>
<% for e in @entries %>
  <tr>
    <td>
    <%= link_to e.entry_text, edit_entry_path(e) %>
    <br>
    Last updated on <%= e.updated_at.to_date %>
    </td>

  </tr>
<% end %>

</tbody>
</table>

</div>

<br>

app/views/entries/new.html.erb
<%- model_class = Entry -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entries/show.html.erb
<%- model_class = Entry -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:entry_text) %>:</strong></dt>
  <dd><%= @entry.entry_text %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              entries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_entry_path(@entry), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              entry_path(@entry),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>