config/routes.rb
Dailyjournal::Application.routes.draw do
  get "sessions/new"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "search" => "entries#index"
  resources :users
  
  resources :entries do
    collection { post :import }
  end

  resources :sessions
  resources :friendships

  root 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base


  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  attr_accessor :password
  before_save :encrypt_password
  
  before_create { generate_token(:auth_token) }
  has_many :entries, :dependent => :destroy

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end 
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    	user
  	else
    	nil
  	end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

def sign_in(user)
    cookies[:auth_token] = user.auth_token
    current_user = user

    Highrise::Base.site = user.site 
    Highrise::Base.user = user.token
    Highrise::Base.format = :xml
  end

  def new 
    if current_user
      redirect_to '/entries'
    else
      @user = User.new
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @entries = @user.entries
  end
 
  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          sign_in @user
          format.html { redirect_to '/entries', notice: 'User was successfully created.' }
          format.json { render action: 'show', status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :site, :token,:email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h3 class="header-title">Daily Journal</h3>



<%= render template: "/layouts/sidebar" %>


<div class="main">
<p class="page-header">Users</p>

<% for user in @users %>
  <div class="user">
    <p>
      <strong><%=h user.email %></strong>
        <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>

      <div class="clear"></div>
    </p>
  </div>
<% end %>

<br>

<h5>Your Friends</h5>
<ul>
  <% for friendship in current_user.friendships %>
  <li>
    <%= h friendship.friend.email %>
    (<%= link_to "remove", friendship, :method => :delete %>)
  </li>
  <% end %>  
</ul>

</div>

app/views/users/login.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<%= form_for(@user, :html => {:class=>'form-signup'}) do |f| %>

  <h2 class="form-signup-heading">Sign Up</h2>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <label for="inputEmail" class="sr-only">Email address</label>
  <input id="inputEmail" name="user[email]" class="form-control" placeholder="Email address" required="" autofocus="" type="email">

  <br>
  <label for="inputPassword" class="sr-only">Password</label>

  <input id="inputPassword" name="user[password]" class="form-control" placeholder="Password" required="" type="password">

    <label for="inputPassword" class="sr-only">Password Confirmation</label>

  <input id="inputPassword" name="user[password_confirmation]" class="form-control" placeholder="Password Confirmation" required="" type="password">

<label for="inputPassword" class="sr-only">Site</label>

  <input id="inputPassword" name="user[site]" class="form-control" placeholder="Site" required="" type="text" value="https://technexusllc.highrisehq.com/">
  <br>

  <label for="inputPassword" class="sr-only">Api token</label>

  <input id="inputPassword" name="user[token]" class="form-control" placeholder="Api token" required="" type="text" value="c18059e427e8f6b6f0ecb4fe2b04445f">

  <br>
  <button class="btn btn-lg btn-primary btn-block" type="submit">

    Sign up

</button>
<% end %>

app/views/users/show.html.erb
<h3 class="header-title">Daily Journal</h3>


<%= render template: "/layouts/sidebar" %>


<div class="main">
<p class="page-header">Public Profile</p>

<table>

<tbody>
<% for e in @entries %>
  <% if (e.visibility == true && @user.friends.where("user_id =?",current_user.id)) || (e.visibility == false && @user.id = current_user.id) %>
  <tr>
    <td>
    <%= e.entry_text %>
    <br>
    Last updated on <%= e.updated_at.to_date %>
    </td>
  </tr>
  <% end %>
<% end %>

</tbody>
</table>





</div>
<br>