config/routes.rb
Dailyjournal::Application.routes.draw do
  get "sessions/new"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "search" => "entries#index"
  resources :users
  
  resources :entries do
    collection { post :import }
  end

  resources :sessions
  resources :friendships

  root 'users#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dailyjournal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="topbar">
      <div class="fill">
        <div class="top_container">

        

      <ul class="nav secondary-nav">
		<div id="user_nav">
		  <% if current_user %>
    		Logged in as <%= current_user.email %>
    	 <%= link_to "Log out", log_out_path %>
  		<% else %>
    		<%= link_to "Sign up", sign_up_path %> or 
    		<%= link_to "Log in", log_in_path %>
  		<% end %>
		</div>
          
       </ul>
    </div>






  </div>
</div>


<br>
<br>

<%= yield %>

</body>
</html>

app/views/layouts/sidebar.html.erb
<div class="sidebar">
<ul>
  <li>
    <%= link_to "Entries", "/entries" %>
  </li>
  <li>
    <%= link_to "Public profile", "/users/#{current_user.id}" %>
  </li>
  <li>
      <%= link_to "Friends","/users" %>
  </li>
</ul>
</div>